/*
 * generated by Xtext 2.16.0
 */
package hu.blackbelt.judo.meta.jsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JslDslStandaloneSetup extends JslDslStandaloneSetupGenerated {

	def static void doSetup() {
		new JslDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
