ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
:icons: font
:KW: [purple]##**
:KWE: **##

// TODO: schedule and init

[judo-req="true",judo-req-id="REQ-SRV-014"]
= Actor
:page-toctitle:Actor

Authentication is the process of verifying a user’s identity and authorization is the process of determining whether an authenticated user has access to a particular resource or service. Authorization is critical for ensuring that only authorized users have access to sensitive data and resources. The following chapters describe JUDO's authentication and authorization process.

An actor represents a generic user of the system and can be used to represent humans or another system. Actors are a special subset of transfer objects. Members of actors can be relations (referred to as access), actions, and event handlers, just like in the case of transfer objects. However, one important difference is that actors do not contain fields.

To define an actor, use the `actor` keyword.

*Syntax:*

[subs="quotes"]
----
[purple]#**actor**# &lt;[purple]##**human**##|[purple]##**system**##> &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##]
    &#x5B;[purple]##**realm**## &lt;realm>]
    &#x5B;[purple]##**claim**## &lt;claim>]
    &#x5B;[purple]##**identity**## &lt;identity>]
    &#x5B;[purple]##**guard**## &lt;guard>][purple]
[purple]##**{**##
    [member] ...
[purple]#**}**#
----

where the <name> is the name of the actor. The <entity> is the entity type of the linked entity instance. The <mapping-field> is the name of the field that refers to the linked entity instance. The linked entity instance is the persistent representation of the user in the application. If there is no linked entity, the user is not represented in the application. A typical case of not represented user is an anonymous user, who shall not be identified within the application.

The <realm> is the name of the security policy domain attached to the actor. The realm is a collection of users who can be authenticated to use the application. The realms and identity management used by JUDO are out of scope of the application. The default realm management application that can be used by a JUDO application is Keycloack, but any OpenID3 compatible identity management application can be easily integrated.

A claim is a name/value pair that contains information about the user. A collection of claims are sent by the realm management application to our application at the time when the user authenticates. The <claim> selects one of the claims, which will be used for user identification in the application.

The <identity> is an expression that selects an identifier field of the mapped <entity>. The type of the field pointed to by <identity> must be string. The <identity> is used to unambiguously identify the user within the application (e.g. find only one instance of the mapped entity) to define the relationship with the user in the <realm>.

The <guard> is a boolean expression that must evaluate to true in order to authenticate the user. To put it more simply, a guard defines a precondition. If the <guard> evaluates to false, the user is not authenticated and an error message is thrown.

// TODO: managed user missing

[NOTE]
====
There is an alternative syntax to define an actor. This alternative is a bit more expressive, although it may be too verbose.

[subs="quotes"]
----
[purple]#**actor**# &lt;[purple]##**human**##|[purple]##**system**##> &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##]
    &#x5B;[purple]##**realm**## "&lt;realm>"]
    &#x5B;[purple]##**claim**## "&lt;claim>"]
    &#x5B;[purple]##**identity**## &lt;identity>]
    &#x5B;[purple]##**guard**## &lt;guard>]
[purple]##**{**##
    [member] ...
[purple]#**}**#
----

====


*Example:*

[source,jsl]
----
actor SalesPersonActor(SalesPerson salesPerson)
    realm "COMPANY"
    claim "email"
    identity salesPerson.email;
----

The above example defines an actor named `SalesPersonActor`. The company's sales staff are managed in the "COMPANY" realm. The salespersons' unique identifier is their email address. During authentication, the system selects the instance of the SalesPerson entities whose email field has the same value as the value of the "email" claim.


[judo-req="true",judo-req-id="REQ-SRV-015"]
== Access

Authorization is the mechanism responsible for granting external users access to specific transfer objects and their actions. In general terms, authorization is a key mechanism for controlling access rights and permissions.

The actors within the application can be considered the embodiment of external users who can access the transfer objects granted to them. That is, an actor exposes the transfer objects to the outside world.

Access definitions within actors are used to expose the application data model quickly and elegantly. The access can have an expression that will be evaluated when the access is invoked from the outside world. Accesses play the same role as relations in transfer objects.

Use the `access` keyword to specify an access within an actor.

*Syntax:*

[subs="quotes"]
----
[purple]#**access**# &lt;transfer>&#x5B;[purple]##**[]**##] &lt;name> &#x5B;[purple]##**<=**## &lt;expression>][purple]#**;**#
----

The access of an actor is the same as the relation of transfer objects. It may be 

*Example:*

[source,jsl]
----
// Bad example
actor system CustomerActor(Customer customer) {
	access CartTransfer myCart <= customer;
	access ProductListTransfer products;
}
----

Defining an actor with no `exports` would let users to authenticate themselves and log into the application. However, they cannot access any resources (services and data) within our application.

The actor object can grant permission to services containing functions by exporting them. After exporting services, the user can call all the functions in the service.

To authorize actors to use services, use `exports` in the actor specification.

*Syntax:*

[subs="quotes"]
----
[purple]#**actor**# &lt;name> [(&lt;entity> &lt;mapping-field>)] &#x5B;[purple]##**exports**## &lt;service>, ...]
    &#x5B;[purple]##**realm**## "&lt;realm>"]
    &#x5B;[purple]##**claim**## "&lt;claim>"]
    &#x5B;[purple]##**identity**## &lt;identity>][purple]#**;**#
----

where the `exports` keyword is followed by a comma-separated list of services.

The actor can export only unmapped services or mapped services that are linked to the same type (or subtype) of entity to which the actor is linked. 

*Example:*

[source,jsl]
----
entity Person {
    field String email;
}

transfer PersonTransfer(Person person) {
    field String email reads salesPerson.email;
}

service ManagerService {
    function PersonTransfer create();
}

actor Manager exports ManagerService;
----

The example above allows the manager to create a new person. To grant permissions to external users, we first need to define entities, transfer objects and services. The Manager actor in this application has no realm or identity, meaning this actor is an anonymous actor. Anonymous actors are publicly available, anyone who knows the URL of the Manager actor interface can invoke the create function. This way, the Manager actor is given access to the ManagerExport's create function, with which the user can create a PersonTransfer.

[judo-req="true",judo-req-id="REQ-SRV-016"]
=== Transfer object export

Besides the actors, the transfer objects can also grant access to service functions by exporting services. For example, if a transfer object represents a customer, its exported services might include the ability to edit the customer's information, place orders, and view order history.

JUDO's security mechanism can be thought of as a logical permission graph that defines the access of external users to resources within the application. The nodes of the permission graph are the actors and instances of the transfer objects. The edges of the graph are the exported service functions.

At the entry point of the permission graph is the actor, which represents the external user, who can access service functions exported by the actor.

Calling the functions exported by the actor, the user receives transfer object instances returned by the functions. Once the user gets a new transfer object instance, they can call the service functions exported by that transfer object (and so on). The entry point to the permission graph is the actor, which represents the external user and allows traversing (by calling functions) to transfer object instances. From each transfer object instance the user can further traverse to other transfer object instances, creating a recursive hierarchy of permissions. As a result of the above, functions exported by transfer objects that cannot be traversed from any actor will not be available to external users.

JUDO's security mechanism also includes a number of built-in security features, such as encryption and secure communication protocols, to ensure the privacy and security of the data being exchanged between external users and the application.

The complete authorization mechanism can be defined by carefully provisioning services to actors and transfer objects. Always be aware of that if a transfer object instance has already been received by an external user, then they are authorized to call the service functions exported by the transfer object.

To export services, use `exports` keyword in the transfer object's specification.

*Syntax:*

[subs="quotes"]
----
[purple]#**transfer**# &lt;name> (&lt;entity> &lt;alias>) &#x5B;[purple]##**exports**## &lt;service>, ...] &#x5B;{
    &#x5B;member] ...
}]
----

The example below shows how a transfer object can export services. Users who received the PersonTransfer object can call the delete function.  This function can only be called by the users who have access to the PersonTransfer object.


*Example:*

[source,jsl]
----
service PersonService(Person person) {
    function void delete();
}

service ManagerService {
    function PersonTransfer[] listPersons();
}

transfer PersonTransfer(Person person) exports PersonService {
    field String email reads salesPerson.email;
}

actor Manager exports ManagerService;

----

[judo-req="true",judo-req-id="REQ-SRV-017"]
=== Guard

A guard is a boolean expression that must evaluate to true in order to continue the execution. To put it more simply, a guard defines a precondition.

Guards can be defined for

* functions,
* services and
* actors.

To add a guard to functions use `guard` as follows. The function guard is evaluated before the function execution. If the function guard evaluates to false, the function is not executed and an error message is thrown.

*Example:*

[source,jsl]
----
service PersonService(Person person) {
    function void delete() guard person.leads.size() == 0;
}
----

The example above defines a guard, and the delete function is not executed if that person has a lead.

// TODO: what is the error message?

To add a guard to services use `guard` as follows. The service guard is a shortcut that assigns the same guard to each function. The service guard is evaluated before each function is executed in the service. If the service guard evaluates to false, the function is not executed and an error message is thrown. If the service guard evaluation is true, then the function guard, if any, is evaluated.

*Example:*

[source,jsl]
----
service PersonService(Person person) guard person.leads.size() == 0 {
    function void delete();
    function Lead[] addLead(Lead lead);
}
----

The example above defines a guard for service, and the functions are not executed and an error is thrown if that person has a lead.

// TODO: add error definition to guards if error is intruduced

To add a guard to actors use `guard` as follows. The actor guard is evaluated before each function call to the application. If the actor guard evaluates to false, none of the application function can be executed and an error message is thrown.

////
Alternative actor guard execution:
The actor guard is evaluated when the user is authenticated by the application. If the actor guard evaluates to false, the user cannot call any function of the application.
////

*Example:*

[source,jsl]
----
actor SalesPersonActor(SalesPerson salesPerson)
    realm "COMPANY"
    identity salesPerson.email
    guard salesPerson.leads.size() > 0;
----

The example above defines a guard for actor, and the salesperson can only invoke the functions if she has at least one lead.
