ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
:icons: font
:KW: [purple]##**
:KWE: **##

// TODO: schedule and init

[judo-req="true",judo-req-id="REQ-SRV-014"]
= Access control
:page-toctitle:Access

Authentication is the process of verifying a user’s identity and authorization is the process of determining whether an authenticated user has access to a particular resource or service. Authorization is critical for ensuring that only authorized users have access to sensitive data and resources. The following chapters describe JUDO's authentication and authorization process.

== Actor

An actor represents a generic user of the system and can be used to represent humans or another system.

To define an actor, use the `actor` keyword. The full list of modifiers can be found in the xref:appx_modifiers.adoc#actor[Appendix].

*Syntax:*

[subs="quotes"]
----
[purple]#**actor**# &lt;name>
    &#x5B;[purple]##**human:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**realm:**##&lt;realm>]
    &#x5B;[purple]##**claim:**##&lt;claim>]
    &#x5B;[purple]##**identity:**##&lt;identity>]
    &#x5B;[purple]##**guard:**##&lt;guard>]
&#x5B;[purple]##**{**##
    &#x5B;member] ...
[purple]##**}**##][purple]#**;**#
----

where the <name> is the name of the actor.

The `human` modifier adds visual representation to the actor and enables the creation of a web application. See <<Human actor>> chapter.

The `realm` is the name of the security policy domain attached to the actor. The realm is a collection of users who can be authenticated to use the application. The realms and identity management used by JUDO are out of scope of the application. The default realm management application that can be used by a JUDO application is Keycloack, but any OpenID3 compatible identity management application can be easily integrated.

A claim is a name/value pair that contains information about the user. A collection of claims are sent by the realm management application to our application at the time when the user authenticates. The `claim` modifier selects one of the claims, which will be used for user identification in the application.

The `identity` is the name of a field in a transfer object. This field must contain the identifier of the authenticated user. The selected identifier field is used to uniquely identify the user within the application (e.g., to find only one instance of the mapped entity) and to define the relationship with the user in the realm.

[IMPORTANT] 
==== 
The field selected by the `identity` modifier must be of type string and must be mapped to an identifier string field in the transfer object's mapped entity.
==== 

If there is no `identity` modifier, the user is not represented in the application. A typical case of not represented user is an anonymous user, who shall not be identified within the application.

The `guard` modifier is a boolean expression that must evaluate to true in order to authenticate the user. To put it more simply, a guard defines a precondition. If the <guard> expression evaluates to false, the user is not authenticated and an error message is thrown.

// TODO: managed user missing

*Example:*

[source,jsl]
----
entity SalesPerson {
    identifier String email;
}

transfer SalesPersonTransfer(SalesPerson salesPerson) {
    field String email <= salesPerson.email set:true;
}

actor SalesPersonActor
    realm:"COMPANY"
    claim:"email-addr"
    identity:SalesPersonTransfer::email;
----

The above example defines an actor named `SalesPersonActor`. The company's sales staff are managed in the "COMPANY" realm. The salespersons' unique identifier is their email address. During authentication, the system selects the instance of the SalesPerson entities whose email field has the same value as the value of the "email" claim.


[judo-req="true",judo-req-id="REQ-SRV-015"]
[judo-req="true",judo-req-id="REQ-SRV-016"]
=== Access

Authorization is the mechanism responsible for granting external users access to specific transfer objects and their actions. In general terms, authorization is a key mechanism for controlling access rights and permissions.

The actors within the application can be considered the embodiment of external users who can access the transfer objects granted to them. That is, an actor exposes the transfer objects to the outside world.

Access definitions within actors are used to expose the application data model quickly and elegantly. The access can have an expression that will be evaluated when the access is invoked from the outside world. Accesses play the same role as relations in transfer objects.

The target of an access is always a mapped transfer object, and the getter expression is mandatory.

Use the `access` keyword to specify an access within an actor.

*Syntax:*

[subs="quotes"]
----
[purple]#**access**# &lt;transfer>&#x5B;[purple]##**[]**##] &lt;name> [purple]##**<=**## &lt;expression>
    &#x5B;[purple]##**eager:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**create:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**delete:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**update:**##([purple]##**true**##|[purple]##**false**##)][purple]#**;**#
----

The full list of modifiers can be found in the xref:appx_modifiers.adoc#actor-access[Appendix].

*Example:*

[source,jsl]
----
actor CustomerActor(Customer customer) {
	access CartTransfer myCart <= Customer
	    .filter(c | c.email == String.getVariable(category = "ACTOR", key = "username"));

	access ProductTransfer[] products <= Product.all();
}
----

In addition to actors, transfer objects can also provide access to other transfer objects. For instance, if a transfer object represents a customer, it allows access to the customer's current orders and order history.

The security mechanism in JUDO can be understood as a logical permission graph that defines how external users can access resources in the application. In this graph, the nodes represent actors and transfer objects, while the edges represent the relationships and actions.

At the starting point of this permission graph is the actor, which represents the external user. When a user gains access to transfer objects offered by an actor, they obtain instances of these transfer objects. Once the user has a new transfer object instance, they can then access transfer objects made available by that specific transfer object (and so on). The initial entry point to the permission graph is the actor representing the external user, enabling traversal through relations to access transfer object instances. Consequently, a hierarchical chain of permissions is established as the user can navigate to various transfer object instances. As a result, transfer objects that cannot be reached from the actor remain unavailable to external users.

The comprehensive authorization mechanism can be established by carefully configuring relationships with transfer objects. It's essential to note that if an external user has already obtained a transfer object instance, they are thereby authorized to access transfer object instances connected through the relationships of that initially obtained transfer object.

JUDO's security mechanism also includes a number of built-in security features, such as encryption and secure communication protocols, to ensure the privacy and security of the data being exchanged between external users and the application.

[judo-req="true",judo-req-id="REQ-SRV-017"]
=== Guard

Guards can be defined for actors. A guard is a boolean expression that must evaluate to true in order to continue the execution. To put it more simply, a guard defines a precondition.

To add a guard to actors use `guard` as follows. The actor guard is evaluated before each request to the application. If the actor guard evaluates to false, none of the transfer objects are available and an error message is thrown.


*Example:*

[source,jsl]
----
actor SalesPersonActor
    realm:"COMPANY"
    claim:"email-addr"
    identity:SalesPersonTransfer::email
    guard salesPerson.leads.size() > 0;
----

The example above defines a guard for the actor, ensuring that the salesperson can only invoke the functions if they have at least one lead.

== Human actor

Human actors are special actors that not only enable transfer object access but also define how these accesses are presented to the user. All concepts and members introduced for simple actors are also valid for human actors. Additionally, human actors may have other types of members described in this chapter.

In the web application, the human actor is represented as the menu of the web application. Access declarations cannot be seen in the menu; however, link, table, and group members are shown in the menu.

To define a human actor use the `actor` keyword with the `human` modifier. This will result in a web application.

*Example:*

[source,jsl]
----
actor SalesPersonActor
    human:true
    realm:"COMPANY"
    claim:"email-addr"
    identity:SalesPersonTransfer::email;
----

=== Link

An actor link is a visual component in a user interface that symbolizes an access to a view. The actor link is represented as a menu item in the web application's menu.

*Syntax:*

[subs="quotes"]
----
[purple]#**link**# &lt;view> &lt;name> [purple]##**<=**## &lt;expression>
    &#x5B;[purple]##**eager:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**create:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**delete:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**update:**##([purple]##**true**##|[purple]##**false**##)]

    &#x5B;[purple]##**label:**##&lt;label>]
    &#x5B;[purple]##**icon:**##&lt;icon>]
    &#x5B;[purple]##**hidden:**##&lt;hidden>][purple]#**;**#
----

In addition to the permission modifiers (See <<Permission modifiers>> chapter), the actor link enables the use of the following visual modifiers.

The `label` modifier requires static text, which is displayed on the menu item.

The `icon` modifier expects static text that is the name of the icon used to display on the menu item. The icon is used to ease the quick identification the menu item. Possible icon names can be found here: https://pictogrammers.com/library/mdi/.

The `hidden` modifier is used to control the visibility of the menu item in the application menu. When applied to an actor link, the modifier ensures that the menu item is not displayed to the user when the menu is rendered. This can be useful for hiding certain menu items based on certain conditions.

The full list of modifiers can be found in the xref:appx_modifiers.adoc#actor-link[Appendix].

=== Table

An actor table is a visual component in a user interface that symbolizes an access to a table. The actor table is represented as a menu item in the web application's menu.

*Syntax:*

[subs="quotes"]
----
[purple]#**table**# &lt;row>[purple]##**[]**## &lt;name> [purple]##**<=**## &lt;expression>
    &#x5B;[purple]##**eager:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**create:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**delete:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**update:**##([purple]##**true**##|[purple]##**false**##)]

    &#x5B;[purple]##**label:**##&lt;label>]
    &#x5B;[purple]##**icon:**##&lt;icon>]
    &#x5B;[purple]##**hidden:**##&lt;hidden>]
    &#x5B;[purple]##**rows:**##&lt;rows>][purple]#**;**#
----

The full list of modifiers can be found in the xref:appx_modifiers.adoc#actor-table[Appendix].

In addition to the permission modifiers (See <<Permission modifiers>> chapter), the actor table enables the use of the following visual modifiers.

The `label` modifier requires static text, which is displayed on the menu item.

The `icon` modifier expects static text that is the name of the icon used to display on the menu item. The icon is used to ease the quick identification the menu item. Possible icon names can be found here: https://pictogrammers.com/library/mdi/.

The `hidden` modifier is used to control the visibility of the menu item in the application menu. When applied to an actor table, the modifier ensures that the menu item is not displayed to the user when the menu is rendered. This can be useful for hiding certain menu items based on certain conditions.

The `rows` modifier sets the number of rows displayed in the table.

=== Group

An actor group is a collection or grouping of related menu items within a menu structure. It helps organize and categorize menu items for easier navigation and accessibility. Menu groups are used to group together related actor link and tables within the application's menu system.

*Syntax:*

[subs="quotes"]
----
[purple]#**group**# &lt;name>
    &#x5B;[purple]##**label:**##&lt;label>]
    &#x5B;[purple]##**icon:**##&lt;icon>]
    &#x5B;[purple]##**hidden:**##&lt;hidden>]
[purple]##**{**##
    [member] ...
[purple]#**}**#[purple]##**;**##
----

where the <name> is the name of the group and the members is a list of contained links, tables, or other groups.

The full list of modifiers can be found in the xref:appx_modifiers.adoc#actor-group[Appendix].

== Permission modifiers

Up until now, we've discussed access to transfer objects, which essentially means the permission to read those objects. However, it's important to note that permission control can extend beyond just reading. We have the flexibility to enhance the rights of access by incorporating additional permissions in the form of modifiers:

* **Create**: This permission allows the creation of new objects. Users with create permission can generate new transfer object instances within the system. For example, a user with create permission might be able to create new customer accounts or add new products to a catalog.

* **Delete**: The delete permission permits the removal or deletion of objects. Users with delete permission can eliminate existing transfer object instances from the system. For instance, this might involve deleting customer accounts or removing products from a catalog.

* **Update**: Update permission grants users the ability to modify or edit existing transfer objects. Users with this permission can make changes to the fields of transfer objects. For example, a user with update permission could edit a customer's contact information or change the status of an order.

By incorporating these create, delete, and update modifiers into the actor accesses and the relationships, we can provide more extensive and more fine-tuned rights to users. This means that in addition to reading, users can also create, modify, or delete data, depending on the permissions granted to them.

The following example demonstrates how an admin user within the system can be granted specific permissions to create, delete, or update customer instances:

*Example:*

[source,jsl]
----
actor AdminActor {
	access CustomerTransfer[] users <= Customer.all()
	    create:true
	    delete:true
	    update:true;
}
----

In this code snippet, we define the AdminActor as an actor representing an admin user. This actor is given access to CustomerTransfer objects. Within this context, the create, update, and delete modifiers are utilized. These modifiers are boolean values, which means they can be set to either `true` or `false`. If their value is set to `true`, it signifies that the permission is granted to the admin user, allowing them to create, update, and delete customer instances. Conversely, if the value is `false` or the modifier is missing the respective permission is not granted.

In the same manner, permissions can also be incorporated into relationships between transfer objects:

*Example:*

[source,jsl]
----
transfer CustomerTransfer(Customer customer) {
    relation OrderTransfer[] orders <= customer.orders
        create:true
        delete:true
        update:true;
}
----

This second example showcases how permissions can be extended to the relationships of transfer objects. Here, we define a CustomerTransfer object with a relationship to OrderTransfer objects. Once again, we employ the create, update, and delete modifiers. These modifiers dictate whether the user who has obtained a CustomerTransfer object is permitted to create, delete, or update the customer's associated orders. If the modifiers are set to `true`, the user can perform these actions, otherwise not.

[IMPORTANT] 
==== 
It is important to note that it is not enough to set the `create` or `delete` permission modifiers to `true` to allow the creation and deletion of related objects. The `update` modifier of the relation's container transfer object must also be set to `true`. The reason is quite obvious, when we add or remove an object of a relation, we also change the container object.
==== 

This approach provides precise control over what actions users, particularly admins, can undertake concerning specific objects and their associated objects. It enhances the system's security and flexibility by allowing the fine-tuning of access permissions.
