ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -
:icons: font
:KW: [purple]##**
:KWE: **##

= Appendix Modifiers
:page-toctitle:Appendix Modifiers
:table-caption-side: "bottom"

== Model

[subs="quotes"]
----
[purple]#**model**# &lt;fq-name>[purple]#**;**#
----

== Import

[subs="quotes"]
----
[purple]#**import**# &lt;model> &#x5B;[purple]##**as**## &lt;alias>][purple]#**;**#
----

== Type

[subs="quotes"]
----
[purple]#**type**# &lt;basetype> &lt;name>
    &#x5B;[purple]##**min-size:**##&lt;min-size>]
    &#x5B;[purple]##**max-size:**##&lt;max-size>]
    &#x5B;[purple]##**regex:**##&lt;regex>]
    
    &#x5B;[purple]##**precision:**##&lt;precision>]
    &#x5B;[purple]##**scale:**##&lt;scale>]
    
    &#x5B;[purple]##**mime-types:**##&lt;mime-types>]
    &#x5B;[purple]##**max-file-size:**##&lt;max-file-size>][purple]#**;**#    
----

.Possible modifiers of type declaration
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type       | Meaning
|min-size      | numeric literal             | Applicable for string types. The minimum size of the text.
|max-size      | numeric literal             | Applicable for string types. The maximum size of the text.
|regex         | string literal              | Applicable for string types. Regular expression of the validation pattern.
|precision     | numeric literal             | Applicable for numeric types. The total number of decimal digits.
|scale         | numeric literal             | Applicable for numeric types. The number of decimal digits that will be stored to the right of the decimal point.
|mime-types    | list of string literals     | Applicable for binary types. A comma separated list of strings representing mime types.
|max-file-size | numeric literal with unit   | Applicable for binary types. The maximum size of the stored file.
|====================

== Enumeration

[subs="quotes"]
----
[purple]#**enum**# &lt;name> [purple]#**{**#
    &lt;literal> [purple]##**=**## &lt;ordinal>[purple]#**;**#
    &#x5B;&lt;literal> [purple]##**=**## &lt;ordinal>[purple]#**;** ...#]
[purple]#**}**#
----

== Entity

[subs="quotes"]
----
[purple]#**entity**# &lt;name> &#x5B;[purple]##**extends**## &lt;entity>[purple]##**,**## ...] 
    &#x5B;[purple]##**abstract:**##([purple]##**true**##|[purple]##**false**##)]
[purple]##**{**##
    [member] ...
[purple]#**}**#
----

.Possible modifiers of entity declaration
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type       | Meaning
|abstract      | boolean literal             | If the entity type is abstract and cannot be instantiated.
|====================

== Entity field

[subs="quotes"]
----
([purple]#**field**#|[purple]#**identifier**#) &lt;primitive> &lt;name> &#x5B;[purple]##**<=**## &lt;expression>]
    &#x5B;[purple]##**required:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**default:**##&lt;default>][purple]#**;**#
----

or

[subs="quotes"]
----
[purple]#**field**# &lt;entity>&#x5B;[purple]##**[]**##] &lt;name>
    &#x5B;[purple]##**required:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**eager:**##([purple]##**true**##|[purple]##**false**##)][purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Modifier name  | Modifier type     | Meaning
|default        | expression returns primitive value  | The default value of the field.
|required       | boolean literal   | If the field value must be specified.
|eager          | boolean literal   | If the fetching strategy is eager.
|====================

== Entity relation

[subs="quotes"]
----
[purple]#**relation**# &lt;entity>&#x5B;[purple]##**[]**##] &lt;name>
    &#x5B;[purple]##**required:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**default:**##&lt;default>]
    &#x5B;[purple]##**opposite:**##&lt;opposite> | [purple]##**opposite-add:**##&lt;opposite>&#x5B;[purple]##**[]**##]]
    &#x5B;[purple]##**eager:**##([purple]##**true**##|[purple]##**false**##)][purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Modifier name  | Modifier type               | Meaning
|required       | boolean literal             | If the relation value must be specified, the modifier cannot be used for collections.
|default        | expression returns entities | The default value of the field.
|opposite       | relation name               | Create a bidirectional relation.
|opposite-add   | relation name               | Create a bidirectional relation with injection.
|eager          | boolean literal             | If the fetching strategy is eager.
|====================

== Query

[subs="quotes"]
----
[purple]#**query**# (&lt;primitive>|&lt;entity>&#x5B;[purple]##**[]**##]) &lt;name> [purple]##**(**##&#x5B;&lt;primitive> &lt;parameter> &#x5B;[purple]##**=**## &lt;value>][purple]##,## ...][purple]##**)**##
    &#x5B;[purple]##**on**## &lt;entity> [purple]##**<=**## &lt;expression>][purple]#**;**#
----

== Transfer

[subs="quotes"]
----
[purple]#**transfer**# &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##] [purple]#**{**#
    &#x5B;member] ...
[purple]#**}**#
----

== Transfer field

[subs="quotes"]
----
[purple]#**field**# &lt;primitive> &lt;name> &#x5B;[purple]##**<=**## &lt;expression>]
    &#x5B;[purple]##**required:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**enabled:**##&lt;enabled>]
    &#x5B;[purple]##**default:**##&lt;default>]
    &#x5B;[purple]##**set:**##([purple]##**true**##|[purple]##**false**##)][purple]#**;**#
----

.Possible modifiers of transfer field
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type                  | Meaning
|required      | boolean literal                        | If the field cannot be undefined.
|enabled       | expression returns boolean     | If the field is enabled for editing.
|default       | expression returns <primitive> | The default value of the field.
|set           | boolean literal                        | If the transfer field is changed, its value will be set into the mapped entity's field.
|====================

== Transfer relation

[subs="quotes"]
----
[purple]#**relation**# &lt;transfer>&#x5B;[purple]##**[]**##] &lt;name> &#x5B;[purple]##**<=**## &lt;expression>]
    &#x5B;[purple]##**required:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**enabled:**##&lt;enabled>]
    &#x5B;[purple]##**default:**##&lt;default>]

    &#x5B;[purple]##**choices:**##&lt;choices>]
    &#x5B;[purple]##**selector:**##&lt;transfer>]

    &#x5B;[purple]##**eager:**##([purple]##**true**##|[purple]##**false**##)]
    
    &#x5B;[purple]##**create:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**delete:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**update:**##([purple]##**true**##|[purple]##**false**##)][purple]#**;**#
----

.Possible modifiers of transfer relation
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type               | Meaning
|required      | boolean literal                     | If the relation cannot be undefined. It is not applicable for collections.
|enabled       | expression returns boolean  | If the relation is enabled for editing.
|default       | expression returns entities | The default list of transfers.
|choices       | expression returns entities | The possible list of transfers to add.
|selector      | transfer object type        | The type of transfer object when the list of choices requested.
|eager         | boolean literal                     | If the fetching strategy is eager.
|create        | boolean literal                     | If create is allowed on this relation.
|delete        | boolean literal                     | If delete is allowed on this relation.
|update        | boolean literal                     | If update is allowed on this relation.
|====================

== Transfer action

[subs="quotes"]
----
[purple]#**action**# &#x5B;&lt;output>|[purple]#**void**#] &lt;name> [purple]##**(**##&#x5B;&lt;parameter>] &#x5B;[purple]##**choices:**##&lt;choices>][purple]##**)**##
    &#x5B;[purple]##**throws**## &lt;error1> &#x5B;[purple]##**,**##&lt;error2>] ...]

    &#x5B;[purple]##**static:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**enabled:**##&lt;enabled>]
    &#x5B;[purple]##**update:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**delete:**##([purple]##**true**##|[purple]##**false**##)][purple]#**;**#
----

.Possible modifiers of transfer action
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type               | Meaning
|static        | expression returns boolean  | If the action can be called with no instance.
|enabled       | expression returns boolean  | If the action is enabled for invocation.
|choices       | expression returns entities | The possible list of input parameter.
|delete        | boolean literal                     | If delete is allowed on the returned transfer object.
|update        | boolean literal                     | If update is allowed on returned transfer object.
|====================

== Transfer event

[subs="quotes"]
----
[purple]#**event**# ([purple]#**create**#|[purple]#**delete**#|[purple]#**fetch**#|[purple]#**initialize**#|[purple]#**update**#) &lt;name> &#x5B;[purple]##**(**##&lt;transfer> &lt;parameter>[purple]##**)**##]
    &#x5B;[purple]##**on:**##([purple]##**before**##|[purple]##**after**##)][purple]##**;**##
----

.Possible modifiers of transfer avent
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type        | Meaning
|on            | `before` or `after`  | If event handler executes before or after the system's original handler.
|====================

== Actor

[subs="quotes"]
----
[purple]#**actor**# &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##]
    &#x5B;[purple]##**human:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**realm:**##&lt;realm>]
    &#x5B;[purple]##**claim:**##&lt;claim>]
    &#x5B;[purple]##**identity:**##&lt;identity>]
    &#x5B;[purple]##**guard:**##&lt;guard>]
[purple]##**{**##
    [member] ...
[purple]#**}**#
----

.Possible modifiers of actor
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type               | Meaning
|human         | boolean literal             | If the actor represents a human.
|realm         | string literal              | The name of the security policy domain.
|claim         | string literal              | The name of the claim contains information for identifying users.
|identity      | expression returns field    | Expression that selects an identifier field of the mapped entity.
|guard         | expression returns boolean  | Expression that must evaluate to true in order to authenticate the user.
|====================

== Actor access

[subs="quotes"]
----
[purple]#**access**# &lt;transfer>&#x5B;[purple]##**[]**##] &lt;name> [purple]##**<=**## &lt;expression>
    &#x5B;[purple]##**enabled:**##&lt;enabled>]

    &#x5B;[purple]##**choices:**##&lt;choices>]
    &#x5B;[purple]##**selector:**##&lt;transfer>]

    &#x5B;[purple]##**eager:**##([purple]##**true**##|[purple]##**false**##)]
    
    &#x5B;[purple]##**create:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**delete:**##([purple]##**true**##|[purple]##**false**##)]
    &#x5B;[purple]##**update:**##([purple]##**true**##|[purple]##**false**##)][purple]#**;**#
----

.Possible modifiers of transfer relation
[options="header", cols="1,1,2", caption-side="bottom"]
|====================
|Modifier name | Modifier type               | Meaning
|enabled       | expression returns boolean  | If the relation is enabled for editing.
|choices       | expression returns entities | The possible list of transfers to add.
|selector      | transfer object type        | The type of transfer object when the list of choices requested.
|eager         | boolean literal                     | If the fetching strategy is eager.
|create        | boolean literal                     | If create is allowed on this relation.
|delete        | boolean literal                     | If delete is allowed on this relation.
|update        | boolean literal                     | If update is allowed on this relation.
|====================
