ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]
// Metadata
:judo-reqprefix: REQ-INTR
// Settings
:idprefix:
:idseparator: -
:icons: font
:KW: [purple]##**
:KWE: **##
:source-highlighter: highlight.js

= Cheatsheet

== Model

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**model**# &lt;name> [purple]#**;**#
----

*Example:*

[source,jsl]
----
model shop;
----

[source,jsl]
----
model judo::example::shop;
----

== Import

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**import**# &lt;model> &#x5B;[purple]##**as**## &lt;alias>] [purple]#**;**#
----

*Example:*

[source,jsl]
----
import judo::types;
----

If no alias is specified, the elements of the imported model can be accessed by their simple name or by their fully qualified name.

[source,jsl]
----
import judo::types as types;
----

If an alias is specified, the elements of the imported model can be accessed by their name with the alias prefix or by their fully qualified name.

== Type

*Syntax:*

[subs="quotes"]
----
[purple]#**type**# &lt;basetype> &lt;name> &#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**type**# &lt;basetype> &lt;name> &#x5B; [purple]#**(**#&lt;parameter name> [purple]#**=**# &lt;parameter value>][purple]#**,**# ...[purple]#**)**# ] [purple]#**;**#
----

*Example:*

[source,jsl]
----
type boolean Boolean;
type date Date;
type time Time;
type timestamp Timestamp;
type numeric Integer precision:9 scale:0;
type numeric Long precision:15 scale:0;
type string String min-size:0 max-size:4000;
----

== Entity

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**entity**# &#x5B;[purple]##**abstract**##] &lt;name> &#x5B;[purple]##**extends**## &lt;entity>[purple]##**,**## ...] &#x5B; [purple]##**{**##
    [member] ...
[purple]#**}**# ] [purple]#**;**#
----

*Example:*

[source,jsl]
----
entity abstract Person extends Customer, User;
----

=== Entity primitive field

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**field**# &#x5B;[purple]##**required**##] &lt;primitive> &lt;name> &#x5B;[purple]##**=**## &lt;default>] [purple]#**;**#
----

*Example:*

[source,jsl]
----
field required String name = "John Doe";
----

=== Entity identifier

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**identifier**# &#x5B;[purple]##**required**##] &lt;primitive> &lt;name> &#x5B;[purple]##**=**## &lt;default>] [purple]#**;**#
----

*Example:*

[source,jsl]
----
identifier required String name = "John Doe";
----

=== Entity composition

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**field**# &#x5B;[purple]##**required**##] &lt;entity>&#x5B;[purple]##**[]**##] &lt;name> [purple]#**;**#
----

*Example:*

[source,jsl]
----
field required Address address;
----

[source,jsl]
----
field Address[] addresses;
----

=== Entity relation


*Syntax:*

[subs="quotes"]
----
[purple]#**relation**# &#x5B;[purple]##**required**##] &lt;entity>&#x5B;[purple]##**[]**##] &lt;name> &#x5B;[purple]##**=**## &lt;default>]  &#x5B; [purple]##**opposite**## [purple]##**:**## &lt;opposite> | [purple]##**opposite-add**## [purple]##**:**## &lt;opposite>&#x5B;[purple]##**[]**##] ] [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**relation**# &#x5B;[purple]##**required**##] &lt;entity>&#x5B;[purple]##**[]**##] &lt;name> &#x5B; [purple]##**opposite**## &lt;opposite> | [purple]##**opposite-add**## &lt;opposite>&#x5B;[purple]##**[]**##] ] [purple]#**;**#
----

*Example:*

[source,jsl]
----
relation required Student student = Student!any() opposite: class;
----

[source,jsl]
----
relation Student[] students = Student!all() opposite-add: class;
----

=== Entity derived primitive

*Syntax:*

[subs="quotes"]
----
[purple]#**field**# &lt;primitive> &lt;name> [purple]##**<=**## &lt;expression> [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**derived**# &lt;primitive> &lt;name> [purple]##**=>**## &lt;expression> [purple]#**;**#
----

=== Entity derived relation

// applicable annotations

*Syntax:*

[subs="quotes"]
----
[purple]#**relation**# &lt;entity>&#x5B;[purple]##**[]**##] &lt;name> [purple]##**<=**## &lt;expression> [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**derived**# &lt;entity>&#x5B;[purple]##**[]**##] &lt;name> [purple]##**=>**## &lt;expression> [purple]#**;**#
----

=== Entity primitive query

*Syntax:*

[subs="quotes"]
----
[purple]#**field**# &lt;primitive> &lt;name> [purple]##**(**##&#x5B;&lt;primitive> &lt;argument> [purple]##**=**## &lt;default>[purple]##,## ...][purple]##**)**## [purple]##**<=**## &lt;expression> [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**query**# &lt;primitive> &lt;name> [purple]##**(**##&#x5B;&lt;primitive> &lt;argument> [purple]##**=**## &lt;default>[purple]##,## ...][purple]##**)**## [purple]##**=>**## &lt;expression> [purple]#**;**#
----

=== Entity relation query

*Syntax:*

[subs="quotes"]
----
[purple]#**relation**# &lt;entity>&#x5B;[purple]##**[]**##] &lt;name> [purple]##**(**##&#x5B;&lt;primitive> &lt;argument> [purple]##**=**## &lt;default>[purple]##,## ...][purple]##**)**## [purple]##**<=**## &lt;expression> [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**query**# &lt;entity>&#x5B;[purple]##**[]**##] &lt;name> [purple]##**(**##&#x5B;&lt;primitive> &lt;argument> [purple]##**=**## &lt;default>[purple]##,## ...][purple]##**)**## [purple]##**=>**## &lt;expression> [purple]#**;**#
----

== Query

*Syntax:*

[subs="quotes"]
----
[purple]#**query**# (&lt;primitive>|&lt;entity>&#x5B;[purple]##**[]**##]) &lt;name> [purple]##**(**##&#x5B;&lt;primitive> &lt;argument> [purple]##**=**## &lt;default>[purple]##,## ...][purple]##**)**## [purple]##**<=**## &lt;expression> [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**query**# (&lt;primitive>|&lt;entity>&#x5B;[purple]##**[]**##]) &lt;name> [purple]##**(**##&#x5B;&lt;primitive> &lt;argument> [purple]##**=**## &lt;default>[purple]##,## ...][purple]##**)**## [purple]##**=>**## &lt;expression> [purple]#**;**#
----

== Transfer

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**transfer**# &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##] &#x5B;{
    &#x5B;member] ...
}] [purple]#**;**#
----

or

[subs="quotes"]
----
[purple]#**transfer**# &lt;name> &#x5B; [purple]#**maps**# &lt;entity> [purple]#**as**# &lt;mapping-field> ] &#x5B;{
    &#x5B;member] ...
}] [purple]#**;**#
----

=== Transfer constructor

No syntax change.

*Syntax:*

[subs="quotes"]
----
[purple]#**constructor**# {
    &#x5B;&lt;field> = &lt;expression>[purple]#**;**#] ...
}
----

=== Transfer primitive field

*Syntax:*

[subs="quotes"]
----
[purple]#**field**# &#x5B;[purple]##**required**##] &lt;primitive> &lt;name> &#x5B;([purple]##**<=**##|[purple]##**<=>**##) &lt;expression>] [purple]#**;**#
----

*Old syntax:*

[subs="quotes"]
----
[purple]#**field**# &#x5B;[purple]##**required**##] &lt;primitive> &lt;name> &#x5B;([purple]##**reads**##|[purple]##**maps**##) &lt;expression>] [purple]#**;**#
----

=== Transfer relation

Removed from service object.

*Syntax:*

[subs="quotes"]
----
[purple]#**relation**# &#x5B;[purple]##**required**##] &lt;transfer>&#x5B;[purple]##**[]**##] &lt;name> &#x5B;([purple]##**<=**##|[purple]##**<=>**##) &lt;expression>]
&#x5B; [purple]##**choices**## [purple]##**:**## &lt;expression> ] [purple]#**;**#
----

=== Transfer function

Removed from service object.

*Syntax:*

[subs="quotes"]
----
[purple]#**function**# &#x5B;&lt;type>|[purple]#**void**#] &lt;name> [purple]##**(**##&#x5B;&lt;parameter>][purple]##**)**## &#x5B;[purple]##**throws**## &lt;error1> &#x5B;, &lt;error2>] ...]
&#x5B; [purple]##**guard**## [purple]##**:**## &lt;expression> ] [purple]#**;**#
----

== View

*Syntax:*

[subs="quotes"]
----
[purple]#**view**# &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##] &#x5B;{
    &#x5B;member] ...
}] [purple]#**;**#
----

=== View constructor

*Syntax:*

[subs="quotes"]
----
[purple]#**constructor**# {
    &#x5B;&lt;field> = &lt;expression>[purple]#**;**#] ...
}
----

=== View primitive field

*Syntax:*

[subs="quotes"]
----
[purple]#**field**# &#x5B;[purple]##**required**##] &lt;primitive> &lt;name> &#x5B;([purple]##**<=**##|[purple]##**<=>**##) &lt;expression>]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================

=== View link

*Syntax:*

[subs="quotes"]
----
[purple]#**link**# &#x5B;[purple]##**required**##] &lt;view> &lt;name> &#x5B;([purple]##**<=**##|[purple]##**<=>**##) &lt;expression>]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|choices        | Row declaration + expression  | The possible values for selection.
|create         | View declaration      | The view to show for creating new element.
|text           | string expression     | The textual representation of the link.
|====================

=== View table

*Syntax:*

[subs="quotes"]
----
[purple]#**table**# &lt;row>[purple]##**[]**## &lt;name> &#x5B;([purple]##**<=**##|[purple]##**<=>**##) &lt;expression>]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|choices        | Row declaration + expression  | The possible values for selection.
|create         | View declaration      | The view to show for creating new element.
|rows           | Numeric literal       | The number of rows shown in the table.
|====================

=== View text

*Syntax:*

[subs="quotes"]
----
[purple]#**text**# &lt;name> [purple]##**<=**## &lt;expression>
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================


=== View group

*Syntax:*

[subs="quotes"]
----
[purple]#**group**# &lt;name> &#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]##**{**##
    [member] ...
[purple]#**}**# [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|frame          | boolean literal       | If the group is surrounded by a frame.
|horizontal     | `left`, `right`, `center`    | The location of elements inside the group. 
|vertical       | `top`, `bottom`, `center`, `stretch` | The location of elements inside the group.
|====================

=== View tabs

*Syntax:*

[subs="quotes"]
----
[purple]#**tabs**# &lt;name> &#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]##**{**##
    [group] ...
[purple]#**}**# [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|frame          | boolean literal       | If the group is surrounded by a frame.
|====================

=== View action

*Syntax:*

[subs="quotes"]
----
[purple]#**action**# &#x5B;&lt;view>|&lt;union>|[purple]#**void**#] &lt;name> [purple]##**(**##&#x5B;&lt;parameter>][purple]##**)**##
&#x5B;[purple]##**throws**## &lt;error1> &#x5B;, &lt;error2>] ...]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|guard          | boolean expression    | If the user is allowed to execute the action.
|resource       | access name           | The name of an access where the returned transfer object is available.
|====================

=== View submit

*Syntax:*

[subs="quotes"]
----
[purple]#**submit**# &#x5B;&lt;view>|&lt;union>|[purple]#**void**#] &lt;name>
&#x5B;[purple]##**throws**## &lt;error1> &#x5B;, &lt;error2>] ...]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|width          | numeric literal       | The logical width of the field.
|====================

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|guard          | boolean expression    | If the user is allowed to submit the view.
|resource       | access name           | The name of an access where the returned transfer object is available.
|====================

== Row

*Syntax:*

[subs="quotes"]
----
[purple]#**row**# &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##] &#x5B; [purple]#**detail**# [purple]#**:**# &lt;view> ] &#x5B;{
    &#x5B;member] ...
}] [purple]#**;**#
----

=== Row column

*Syntax:*

[subs="quotes"]
----
[purple]#**column**# &lt;primitive> &lt;name> &#x5B;([purple]##**<=**##|[purple]##**<=>**##) &lt;expression>]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|====================


=== Row action

See <<View action>>.

== Actor

*Syntax:*

[subs="quotes"]
----
[purple]#**actor**# &lt;[purple]##**human**##|[purple]##**system**##> &lt;name> &#x5B;[purple]##**(**##&lt;entity> &lt;mapping-field>[purple]##**)**##]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ...
&#x5B;[purple]##**{**##
    &#x5B;member] ...
[purple]##**}**##] [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|realm          | string literal        | The name of the realm.
|claim          | string literal        | The name of the claim.
|identity       | attribute selection expression    | The attribute of the mapped entity that serves as the identifier against the claim.
|guard          | boolean expression    | The condition to allow the external user to access the services.
|====================

=== Actor group

A group can contain only menu elements.

*Syntax:*

[subs="quotes"]
----
[purple]#**group**# &lt;name> &#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]##**{**##
    [member] ...
[purple]#**}**# [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|====================

=== Actor menu

*Syntax:*

[subs="quotes"]
----
[purple]#**menu**# &lt;view> &lt;name> &#x5B;[purple]##**<=**## &lt;expression>]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----


[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|label          | string literal        | The label to show for the field.
|icon           | string literal        | the name of the icon to show for the field.
|enabled        | boolean expression    | If the field is enabled for editing.
|hidden         | boolean expression    | If the field is shown to the user.
|====================

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|guard          | boolean expression    | The condition to allow the external user to access the service.
|====================

=== Actor resource

*Syntax:*

[subs="quotes"]
----
[purple]#**resource**# &lt;view> &lt;name> &#x5B;[purple]##**<=**## &lt;expression>]
&#x5B;&lt;parameter name> [purple]#**:**# &lt;parameter value>] ... [purple]#**;**#
----

[options="header", cols="1,1,2"]
|====================
|Parameter name | Parameter type        | Meaning
|guard          | boolean expression    | The condition to allow the external user to access the service.
|====================
