<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsl</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
    <key>repository</key>
    <dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#transfer-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#view-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#row-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#actor-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#model</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#membersNotInEntity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lambdaExpression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(self)\b</string>
					<key>name</key>
					<string>keyword.control.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?|:</string>
					<key>name</key>
					<string>keyword.control.ternary.jsl</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
					<key>name</key>
					<string>keyword.operator.comparison.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\-|\+|\*|\/|div|mod</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>not|and|or|implies</string>
					<key>name</key>
					<string>keyword.operator.logical.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.control.jsl</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(type)\b\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.class.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.type.typeDeclaration.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#primitives</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter-pair</string>
						</dict>				
					</array>
				</dict>
			</array>
		</dict>
		<key>parameter-pair</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\w+(-\w+)*)\s*(:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.typeDeclaration.jsl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.arrow.jsl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#TypeWithModelName</string>
				</dict>
			</array>
		</dict>
		<key>model</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(model)\b </string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.model.modelDeclaration.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameInModelDeclaration</string>
						</dict>					
					</array>
				</dict>
			</array>
		</dict>
		<key>import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(import)\b </string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.import.importLibreries.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\w+)(::)</string>
							<key>captures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>support.class.namespaceName.jsl</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.jsl</string>
									</dict>
								</dict>
						</dict>
						<dict>
							<key>begin</key>
							<string>\w+</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>as</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(?=;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\w+</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>support.variable.alliasName.jsl</string>
												</dict>
											</dict>
											<key>end</key>
											<string>(?=;)</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>annotations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@[^ (]+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.annotation.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation.begin.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation.end.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.annotation.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.other.key.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.jsl</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\w*)\s*(=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.property.jsl</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>@\w*</string>
					<key>name</key>
					<string>storage.type.annotation.jsl</string>
				</dict>
			</array>
		</dict>
		<key>primitives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(boolean|binary|string|numeric|date|time|timestamp)\b\s+(\w+)?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.primitives.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.typeName.jsl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>membersInEntity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(identifier)\b(\s+required)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.entityFieldOrIdentifierMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameInIdentifier</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(field)\b(\s+required)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.entityFieldMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameInField</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(relation)\b(\s+required)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.entityRelationMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameInRelation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>membersNotInEntity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(query)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>name</key>
					<string>meta.entityQueryMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\[\])?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.typeName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#parametersInQuery</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#lambdaExpression</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>parametersInQuery</key>
		<dict>
			<key>patterns</key>
			<array>
					<dict>
						<key>begin</key>
						<string>\(</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.section.parameter.begin.jsl</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(?=\))</string>
						<key>name</key>
						<string>meta.paramters.in.jsl</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#modelNameInParameters</string>
							</dict>
						</array>
					</dict>
			</array>
		</dict>
		<key>lambdaExpression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;=</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>storage.type.function.arrow.jsl</string>
							</dict>
						</dict>	
						<key>name</key>
						<string>meta.meta.lambdaExpressionBody.in.jsl.jsl</string>
						<key>end</key>
						<string>(?=;)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#expressions</string>
							</dict>
						</array>
				</dict>
			</array>
		</dict>
		<key>defaultValueExpression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>=</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.assignment.jsl</string>
							</dict>
						</dict>	
						<key>name</key>
						<string>meta.meta.defaultValueExpressionBody.in.jsl.jsl</string>
						<key>end</key>
						<string>(?=;)</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#expressions</string>
							</dict>
						</array>
				</dict>
			</array>
		</dict>
		<key>terminal-signal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.control.jsl</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:(0[0-7]+)L?)</string>
					<key>name</key>
					<string>constans.numberic.octal.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(\\d+\\.\\d*(e[\\-\\+]?\\d+)?))(?=[^a-zA-Z_])</string>
					<key>name</key>
					<string>constans.numberic.float.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[^0-9a-zA-Z_])(?i:(\\.\\d+(e[\\-\\+]?\\d+)?))</string>
					<key>name</key>
					<string>constans.numberic.float.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(\\d+e[\\-\\+]?\\d+))</string>
					<key>name</key>
					<string>constans.numberic.float.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:([1-9]+[0-9]*|0)L)</string>
					<key>name</key>
					<string>constant.numeric.integer.long.decimal.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([1-9]+[0-9]*|0)</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.jsl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>end</key>
					<string>\"</string>
					<key>name</key>
					<string>string.quoted.double.states</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\`</string>
					<key>end</key>
					<string>\`</string>
					<key>name</key>
					<string>string.quoted.double.states</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\\b</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.jsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+\#(\w+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.enummember</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>enum-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(enum)\s+(\w+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.enum.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.entity.jsl</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.enum.end.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#enum-block-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>enum-block-body</key>
		<dict>
			<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.enum.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.enitity.body.java</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(\w+)\s*=</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>variable.other.enummember</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.assignment.jsl</string>
										</dict>
									</dict>									
								</dict>
								<dict>
									<key>include</key>
									<string>#literals</string>				
								</dict>
								<dict>
									<key>include</key>
									<string>#terminal-signal</string>				
								</dict>
							</array>
					</dict>
				</array>
		</dict>
		<!-- ENTITY -->
		<key>entity-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(entity)\b(\s+abstract)?\s+(\w+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.entityName.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.entity.jsl</string>
					<key>end</key>
					<string>(})|(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.entity.end.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>extends</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.extends.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={|;)</string>
							<key>name</key>
							<string>meta.definition.entity.inherited.classes.end.jsl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#entity-inheretend</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
								<key>beginCaptures</key>
								<dict>
									<key>0</key>
									<dict>
										<key>name</key>
										<string>punctuation.section.entity.begin.jsl</string>
									</dict>
								</dict>
								<key>end</key>
								<string>(?=})</string>
								<key>name</key>
								<string>meta.enitity.body.java</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#entity-body</string>
									</dict>
								</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>entity-body</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#membersInEntity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lambdaExpression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
			</array>
		</dict>
		<!-- TRANSFER -->
		<key>transfer-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(transfer)\b\s+(\w+)?\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.transferName.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tranfer.jsl</string>
					<key>end</key>
					<string>(})|(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.entity.end.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modifiersRulesForTransferAndView</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.transfer.body.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.transfer.body.end.jsl</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.transfer.body.java</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#transfer-body</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modifiersRulesForTransferAndView</key>	
		<dict>
			<key>patterns</key>
			<array>
				<!-- regular mapping field -->
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.mappedElement.begin.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\))</string>
					<key>name</key>
					<string>meta.mappedElement.in.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameInParameters</string>
						</dict>
					</array>
				</dict>
				<!-- alternativ mapping field -->
				<dict>
					<key>begin</key>
					<string>maps</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;|{)</string>
					<key>name</key>
					<string>meta.mappedElement.in.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\w+</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={|;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<!-- as -->
									<key>begin</key>
									<string>as</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(?={|;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\w+</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>support.variable.alliasName.jsl</string>
												</dict>
											</dict>
											<key>end</key>
											<string>(?={|;)</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>transfer-body</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#membersInTransfer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
				<dict>
					<key>include</key>
					<string>#annotations</string>				
				</dict>
			</array>
		</dict>
		<key>membersInTransfer</key>
		<dict>
			<key>patterns</key>
			<array>
				<!-- field and relation -->
				<dict>
					<key>begin</key>
					<string>\b(field|relation)\b(\s+required)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.transferFieldAndRelationMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\[\])?(\s+\w+)?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.transferName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>variable.other.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<!-- <=>  and <= -->
									<key>begin</key>
									<string>(&lt;=&gt;|&lt;=)</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.transferReadsAndMapsFieldAndRelation.jsl</string>
									<key>end</key>
									<string>(?=;|{)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#expressions</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#choices</string>
										</dict>	
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#choices</string>
								</dict>	
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#constructor-destrtuctor</string>				
				</dict>
				<!--  submmit, action -->
				<dict>
					<key>begin</key>
					<string>\b(submit|action)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.transferSubmitAndActionMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\[\])?(\s+\w+)?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.typeName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>variable.other.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#parametersInQuery</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>choices</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(choices)\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.arrow.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;|{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>guard</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>guard</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;|{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<!-- VIEW -->
		<key>view-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(view)\b\s+(\w+)?\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.transferName.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tranfer.jsl</string>
					<key>end</key>
					<string>(})|(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.entity.end.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modifiersRulesForTransferAndView</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.transfer.body.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.transfer.body.end.jsl</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.transfer.body.java</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#view-body</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>view-body</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#membersInView</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
				<dict>
					<key>include</key>
					<string>#annotations</string>				
				</dict>
			</array>
		</dict>
		<key>membersInView</key>
		<dict>
			<key>patterns</key>
			<array>
				<!-- destructor, constructor -->
				<dict>
					<key>include</key>
					<string>#constructor-destrtuctor</string>				
				</dict>
				<!--  text -->
				<dict>
					<key>begin</key>
					<string>\b(text)\b(\s+\w+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.viewTextMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<!-- <= -->
									<key>begin</key>
									<string>(&lt;=)</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.transferReadsFieldAndRelation.jsl</string>
									<key>end</key>
									<string>(?=;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#expressions</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#parameter-pair</string>
										</dict>	
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#parameter-pair</string>
								</dict>	
							</array>
						</dict>
					</array>
				</dict>
				<!-- field, link -->
				<dict>
					<key>begin</key>
					<string>\b(field|link)\b(\s+required\b)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.viewTextMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\s+\w+)?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={|;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<!-- <=  and <=> -->
									<key>begin</key>
									<string>(&lt;=&gt;|&lt;=)</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.viewMapsOrReadFieldAndLinkScope.jsl</string>
									<key>end</key>
									<string>(?=;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#expressions</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#parameter-pair</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#parameter-pair</string>
								</dict>	
							</array>
						</dict>
					</array>
				</dict>
				<!-- table -->
				<dict>
					<key>begin</key>
					<string>\b(table)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.viewTextMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\[\])?(\s+\w+)?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.typeName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>variable.other.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={|;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<!-- <=  and <=> -->
									<key>begin</key>
									<string>(&lt;==&gt;|&lt;=)</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.viewMapsOrReadFieldAndLinkScope.jsl</string>
									<key>end</key>
									<string>(?=;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#expressions</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#parameter-pair</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#parameter-pair</string>
								</dict>	
							</array>
						</dict>
					</array>
				</dict>
				<!--  submmit, action -->
				<dict>
					<key>begin</key>
					<string>\b(submit|action)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.transferSubmitAndActionMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\[\])?(\s+\w+)?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.typeName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>variable.other.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#parametersInQuery</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#parameter-pair</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tabs</string>
				</dict>
			</array>
		</dict>
		<key>group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(group)\b(\s+\w+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.viewGroupDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameter-pair</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.enum.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.group.body.java</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#view-body</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tabs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(tabs)\b(\s+\w+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.ConstructorDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameter-pair</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.enum.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.group.body.java</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#group</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constructor-destrtuctor</key>
		<dict>
			<key>patterns</key>
			<array>
				<!-- constructor -->
				<dict>
					<key>begin</key>
					<string>\b(constructor)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.ConstructorDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>((self).)?(\w+)\s*(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.ConstructorFieldDeclaration.jsl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expressions</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<!-- destructor,initializer -->
				<dict>
					<key>begin</key>
					<string>\b(destructor|initializer)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.DeconstructorAndiInitializerDeclarationScope.jsl</string>
				</dict>
			</array>
		</dict>
		<!-- ROW -->
		<key>row-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(row)\b\s+(\w+)?\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.rowName.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tranfer.jsl</string>
					<key>end</key>
					<string>(})|(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.entity.end.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modifiersRulesForRow</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.transfer.body.begin.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.transfer.body.end.jsl</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.transfer.body.java</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#keywords</string>
								</dict>
								<!-- column -->
								<dict>
									<key>begin</key>
									<string>\b(column)\b</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>end</key>
									<string>;</string>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.viewTextMemberDeclarationScope.jsl</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#modelNameSpace</string>
										</dict>
										<dict>
											<key>begin</key>
											<string>(\w+)(\s+\w+)?</string>
											<key>beginCaptures</key>
											<dict>
												<key>1</key>
												<dict>
													<key>name</key>
													<string>support.class.namespaceName.jsl</string>
												</dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>variable.other.jsl</string>
												</dict>
											</dict>
											<key>end</key>
											<string>(?={|;)</string>
											<key>patterns</key>
											<array>
												<dict>
													<!-- <=  and <=> -->
													<key>begin</key>
													<string>(&lt;=&gt;|&lt;=)</string>
													<key>beginCaptures</key>
													<dict>
														<key>1</key>
														<dict>
															<key>name</key>
															<string>keyword.control.jsl</string>
														</dict>
													</dict>
													<key>name</key>
													<string>meta.viewMapsOrReadFieldAndLinkScope.jsl</string>
													<key>end</key>
													<string>(?=;)</string>
													<key>patterns</key>
													<array>
														<dict>
															<key>include</key>
															<string>#expressions</string>
														</dict>
														<dict>
															<key>include</key>
															<string>#parameter-pair</string>
														</dict>
													</array>
												</dict>
												<dict>
													<key>include</key>
													<string>#parameter-pair</string>
												</dict>	
											</array>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#literals</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#terminal-signal</string>				
								</dict>
								<dict>
									<key>include</key>
									<string>#annotations</string>				
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modifiersRulesForRow</key>	
		<dict>
			<key>patterns</key>
			<array>
				<!-- regular mapping field -->
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.mappedElement.begin.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\))</string>
					<key>name</key>
					<string>meta.mappedElement.in.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameInParameters</string>
						</dict>
					</array>
				</dict>
				<!-- alternativ mapping field -->
				<dict>
					<key>begin</key>
					<string>maps</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;|{)</string>
					<key>name</key>
					<string>meta.mappedElement.in.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\w+</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={|;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<!-- as -->
									<key>begin</key>
									<string>as</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(?={|;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\w+</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>support.variable.alliasName.jsl</string>
												</dict>
											</dict>
											<key>end</key>
											<string>(?={|;)</string>
											<key>pattern</key>
											<array>
												<dict>
													<key>include</key>
													<string>#parameter-pair</string>
												</dict>	
											</array>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-pair</string>
				</dict>	
			</array>
		</dict>
		<!-- ACTOR -->
		<key>actor-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(actor)(\s+human|system)?(\s+\w+)?\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.types.class.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.actorName.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tranfer.jsl</string>
					<key>end</key>
					<string>(})|(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modifiersInActor</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modifiersInActor</key>	
		<dict>
			<key>patterns</key>
			<array>
				<!-- regular mapping field -->
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.mappedElement.begin.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\))</string>
					<key>name</key>
					<string>meta.mappedElement.in.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameInParameters</string>
						</dict>
					</array>
				</dict>
				<!-- alternativ mapping field -->
				<dict>
					<key>begin</key>
					<string>maps</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;|{)</string>
					<key>name</key>
					<string>meta.mappedElement.in.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\w+</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?={|;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<!-- as -->
									<key>begin</key>
									<string>as</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(?={|;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>\w+</string>
											<key>beginCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>support.variable.alliasName.jsl</string>
												</dict>
											</dict>
											<key>end</key>
											<string>(?={|;)</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>#parameter-pair-actor</string>
												</dict>
												<dict>
													<key>include</key>
													<string>#actorBody</string>
												</dict>
											</array>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-pair-actor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#actorBody</string>
				</dict>
			</array>
		</dict>
		<key>actorBody</key>	
		<dict>
			<key>patterns</key>
			<array>
			<dict>
				<key>begin</key>
				<string>{</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.actor.body.begin.jsl</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=})</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.actor.body.end.jsl</string>
					</dict>
				</dict>
				<key>name</key>
				<string>meta.actor.body.java</string>
				<key>patterns</key>
				<array>
					<!-- group -->
					<dict>
						<key>begin</key>
						<string>\b(group)\b(\s+\w+)?</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.jsl</string>
							</dict>
						</dict>
						<key>end</key>
						<string>}</string>
						<key>name</key>
						<string>meta.actorGroupMemberDeclarationScope.jsl</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#parameter-pair</string>
							</dict>
							<dict>
								<key>begin</key>
								<string>{</string>
								<key>beginCaptures</key>
								<dict>
									<key>0</key>
									<dict>
										<key>name</key>
										<string>punctuation.section.enum.begin.jsl</string>
									</dict>
								</dict>
								<key>end</key>
								<string>(?=})</string>
								<key>name</key>
								<string>meta.group.body.java</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#actor-menu</string>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
					<!--  acces -->
					<dict>
						<key>begin</key>
						<string>\b(acces)\b</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.control.jsl</string>
							</dict>
						</dict>
						<key>end</key>
						<string>;</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>keyword.control.jsl</string>
							</dict>
						</dict>
						<key>name</key>
						<string>meta.actorAccesMemberDeclarationScope.jsl</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#modelNameSpace</string>
							</dict>
							<dict>
								<key>begin</key>
								<string>(\w+)(\[\])?(\s+\w+)?</string>
								<key>beginCaptures</key>
								<dict>
									<key>1</key>
									<dict>
										<key>name</key>
										<string>support.class.typeName.jsl</string>
									</dict>
									<key>2</key>
									<dict>
										<key>name</key>
										<string>keyword.control.jsl</string>
									</dict>
									<key>3</key>
									<dict>
									<key>name</key>
									<string>variable.other.jsl</string>
								</dict>
								</dict>
								<key>end</key>
								<string>(?=;)</string>
								<key>patterns</key>
								<array>
									<dict>
										<!-- <= -->
										<key>begin</key>
										<string>(&lt;=)</string>
										<key>beginCaptures</key>
										<dict>
											<key>1</key>
											<dict>
												<key>name</key>
												<string>keyword.control.jsl</string>
											</dict>
										</dict>
										<key>name</key>
										<string>meta.actorGetterExpressionMemberDeclarationScope.jsl</string>
										<key>end</key>
										<string>(?=;)</string>
										<key>patterns</key>
										<array>
											<dict>
												<key>include</key>
												<string>#expressions</string>
											</dict>
										</array>
									</dict>
								</array>
							</dict>
						</array>
					</dict>
					<dict>
						<key>include</key>
						<string>#actor-menu</string>
					</dict>
				</array>
				</dict>
			</array>
		</dict>
		<key>actor-menu</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(menu)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.actorMenuMemberDeclarationScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#modelNameSpace</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(\[\])?(\s+\w+)?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.typeName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>variable.other.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<!-- <= -->
									<key>begin</key>
									<string>(&lt;=)</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.control.jsl</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.actorGetterExpressionMemberDeclarationScope.jsl</string>
									<key>end</key>
									<string>(?=;)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#expressions</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#parameter-pair</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#parameter-pair</string>
								</dict>	
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>expressions</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lambdaExpression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal-signal</string>				
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>				
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>				
				</dict>
				<dict>
					<key>include</key>
					<string>#modelName</string>				
				</dict>
			</array>
		</dict>
		<key>entity-inheretend</key>	
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modelNameSpace</string>				
				</dict>
				<dict>
					<key>match</key>
					<string>(\w+)\s*\,</string>
					<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>entity.other.inherited-class.inheritendEntityName.jsl</string>
							</dict>
						</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\w+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.inheritendEntityName.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?={|;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>				
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.jsl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>/\*\*/</string>
					<key>name</key>
					<string>comment.block.empty.jsl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>parameter-pair-actor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(realm|claim)\s*(:)\s*(\".*\")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.arrow.jsl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.states</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(identity|guard)\s*(:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.arrow.jsl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.jsl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.jsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.jsl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modelName</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\w+)(::)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.namespaceName.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((\w+)(?=[^:]))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.entityName.jsl</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>(\w+)(::)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modelNameInModelDeclaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modelNameSpace</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\w+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.class.namespaceName.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
				</dict>
			</array>
		</dict>
		<key>modelNameInIdentifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modelNameSpace</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)(\[\])?(\s+\w+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.typeName.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>		
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#defaultValueExpression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modelNameInField</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modelNameSpace</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)(\[\])?(\s+\w+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.typeName.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>		
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parametersInQuery</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lambdaExpression</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#defaultValueExpression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modelNameInRelation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modelNameSpace</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)(\[\])?(\s+\w+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.typeName.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parametersInQuery</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lambdaExpression</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>=</string>
								<key>beginCaptures</key>
								<dict>
									<key>0</key>
									<dict>
										<key>name</key>
										<string>keyword.operator.assignment.jsl</string>
									</dict>
								</dict>	
								<key>name</key>
								<string>meta.meta.defaultValueExpressionBody.in.jsl.jsl</string>
								<key>end</key>
								<string>(?=;)</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>#expressions</string>
									</dict>
									<dict>
										<key>include</key>
										<string>#oppositeAndOppositeAdd</string>
									</dict>
								</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#oppositeAndOppositeAdd</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>oppositeAndOppositeAdd</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(opposite-add|opposite)\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.arrow.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=;)</string>
				</dict>
			</array>
		</dict>
		<key>modelNameInParameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modelNameSpace</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.typeName.jsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\,)|(?=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\w+)\s*=</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.typeDeclaration.jsl</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>include</key>
							<string>#literals</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modelNameSpace</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\w+)(::)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.namespaceName.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>TypeWithModelName</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\w+)(::)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.typeName.jsl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jsl</string>
						</dict>
					</dict>	
					<key>end</key>
					<string>(\w+)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.typeName.jsl</string>
						</dict>
					</dict>	
					<key>name</key>
					<string>meta.TypeWithModelNameScope.jsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\w+)(::)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.class.namespaceName.jsl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jsl</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Z]\w+)[^:]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.namespaceName.jsl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jsl</string>
	<key>uuid</key>
	<string>9E6E7290-F2E8-4D58-97E2-08CBBB3EB7E8</string>
</dict>
</plist>
