/*
 * generated by Xtext 2.32.0
 */
package hu.blackbelt.judo.meta.jsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link JslDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractJslDslWebModule extends DefaultWebModule {

}
