/**
 * generated by Xtext 2.32.0
 */
package hu.blackbelt.judo.meta.jsl.web;

import com.google.inject.Injector;
import hu.blackbelt.judo.meta.jsl.JslDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class JslDslWebSetup extends JslDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nJslDslWebModule cannot be resolved.");
  }
}
