/**
 * generated by Xtext 2.26.0
 */
package hu.blackbelt.judo.meta.jsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.blackbelt.judo.meta.jsl.JslDslRuntimeModule;
import hu.blackbelt.judo.meta.jsl.JslDslStandaloneSetup;
import hu.blackbelt.judo.meta.jsl.ide.JslDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class JslDslWebSetup extends JslDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    JslDslRuntimeModule _jslDslRuntimeModule = new JslDslRuntimeModule();
    JslDslIdeModule _jslDslIdeModule = new JslDslIdeModule();
    JslDslWebModule _jslDslWebModule = new JslDslWebModule();
    return Guice.createInjector(Modules2.mixin(_jslDslRuntimeModule, _jslDslIdeModule, _jslDslWebModule));
  }
}
