/*
 * generated by Xtext 2.31.0
 */
package hu.blackbelt.judo.meta.jsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class JslDslWebModule extends AbstractJslDslWebModule {
}
