/*
 * generated by Xtext 2.18.0
 */
package hu.blackbelt.judo.meta.jsl.ui.contentassist

import com.google.inject.Inject
import org.eclipse.xtext.CrossReference
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor
import org.eclipse.xtext.Assignment
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext
import hu.blackbelt.judo.meta.jsl.jsldsl.EntityRelationOpposite
import hu.blackbelt.judo.meta.jsl.util.JslDslModelExtension
import hu.blackbelt.judo.meta.jsl.jsldsl.EntityDeclaration
import org.eclipse.xtext.Keyword
import java.util.Set
import com.google.common.collect.ImmutableSet
import hu.blackbelt.judo.meta.jsl.jsldsl.ModelDeclaration
import hu.blackbelt.judo.meta.jsl.jsldsl.Expression
import org.eclipse.xtext.RuleCall
import org.eclipse.xtext.AbstractRule
import hu.blackbelt.judo.meta.jsl.jsldsl.EntityRelationDeclaration
import hu.blackbelt.judo.meta.jsl.jsldsl.SimpleTransferDeclaration
import hu.blackbelt.judo.meta.jsl.jsldsl.UIViewDeclaration
import hu.blackbelt.judo.meta.jsl.jsldsl.UIRowDeclaration
import hu.blackbelt.judo.meta.jsl.jsldsl.UIMenuDeclaration

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class JslDslProposalProvider extends AbstractJslDslProposalProvider {
    // TODO: https://stackoverflow.com/questions/47005235/customizing-content-proposal-in-xtext-for-web-editors
    @Inject extension JslDslModelExtension

    public static Set<String> FILTERED_KEYWORDS = ImmutableSet.of("lambda", "function");

    public static Set<String> FILTERED_TERMINALS = ImmutableSet.of("{", "}", ";", "(", ")", "+", "-", "*", "/", "@",
                                                                  "!=", "<", ">", ">=", "==", "?", "^",
                                                                  "and", "div", "implies", "mod", "or", "xor");

    override completeKeyword(Keyword keyword, ContentAssistContext contentAssistContext, ICompletionProposalAcceptor acceptor) {
        if (FILTERED_KEYWORDS.contains(keyword.getValue()) && contentAssistContext.currentModel instanceof ModelDeclaration) {
            // don't propose keyword
            return;
        }

        if (FILTERED_TERMINALS.contains(keyword.getValue())) {
            // don't propose keyword
            return;
        }

        if (keyword.getValue().equals("self") &&
            contentAssistContext.currentNode.semanticElement.parentContainer(Expression) !== null &&
            contentAssistContext.currentNode.semanticElement.parentContainer(EntityDeclaration) === null
        ) {
            // don't propose keyword
            return;
        }

        super.completeKeyword(keyword, contentAssistContext, acceptor);
    }

	override completeRuleCall(RuleCall ruleCall, ContentAssistContext contentAssistContext,
			ICompletionProposalAcceptor acceptor) {

		var AbstractRule calledRule = ruleCall.getRule();
		
		if (calledRule.alternatives instanceof Keyword) {
			var Keyword keyword = calledRule.alternatives as Keyword;
			completeKeyword(keyword, contentAssistContext, acceptor)
		}

		super.completeRuleCall(ruleCall, contentAssistContext, acceptor)
	}

    override completeEntityRelationOppositeReferenced_OppositeType(EObject model, Assignment assignment,
        ContentAssistContext context, ICompletionProposalAcceptor acceptor
    ) {
        // System.out.println("model: " + model + " assignment: " + assignment + " context: " + context)
        lookupCrossReference((assignment.getTerminal() as CrossReference), context, acceptor,
            [ ((model as EntityRelationOpposite).eContainer as EntityRelationDeclaration)
                .isSelectableForRelation(EObjectOrProxy as EntityRelationDeclaration)
            ]
        );
    }

    override completeEntityDeclaration_Extends(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
        // System.out.println(" - model: " + model + " assignment: " + assignment + " context: " + context)
        lookupCrossReference((assignment.getTerminal() as CrossReference), context, acceptor,
            [
                val entity = model as EntityDeclaration;
                val proposedEntity = EObjectOrProxy as EntityDeclaration
                // System.out.println(" --- Obj: " + EObjectOrProxy + " - " + superEntities.join(", "))

                proposedEntity !== entity && !proposedEntity.superEntityTypes.contains(entity)
            ]
        );
    }

	override completeNamed_Name(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
        //System.out.println("model: " + model + " assignment: " + assignment + " context: " + context)
		super.completeNamed_Name(model, assignment, context, acceptor)
		
		if (model instanceof SimpleTransferDeclaration && (model as SimpleTransferDeclaration).name === null) {
		  	acceptor.accept(createCompletionProposal("Transfer", context));
			
			for (e : (model.eContainer as ModelDeclaration).entityDeclarations) {
				var String display = e.name + "Transfer";
				var String proposal = display
				proposal += "(" + e.name + " " + e.name.toFirstLower +") {\n";

				proposal += "\t// fields\n"

				for (f : e.fields) {
					proposal += "\tfield " + f.referenceType.name + " " + f.name + " " + (f.getterExpr === null ? "<=>" : "<=") + " " + e.name.toFirstLower + "." + f.name + (f.required ? " required" : "") + ";\n"
				}

				proposal += "\n\t// relations\n"

				for (r : e.relations) {
					proposal += "\trelation " + r.referenceType.name + "Transfer" + (r.many ? "[]" : "" ) + " " + r.name + " <= " + e.name.toFirstLower + "." + r.name + (r.getterExpr === null ? " create update delete" : "") + ";\n"
				}

				proposal += "}"
				
		  		acceptor.accept(createCompletionProposal(proposal, display, null, context));
			}
  		}

		if (model instanceof UIViewDeclaration && (model as UIViewDeclaration).name === null) {
		  	acceptor.accept(createCompletionProposal("View", context));
			
			for (t : (model.eContainer as ModelDeclaration).transferDeclarations) {
				var String display = t.name + ((model as UIViewDeclaration).form ? "Form" : "View");
				var String proposal = display
				proposal += "(" + t.name + " " + t.name.toFirstLower +") {\n";

				proposal += "\t// widgets\n"

				for (f : t.fields) {
					proposal += "\twidget " + f.referenceType.name + " " + f.name + " <= " + " " + t.name.toFirstLower + "." + f.name + ";\n"
				}

				proposal += "\n\t// links\n"

				for (r : t.relations.filter[r | !r.many]) {
					proposal += "\tlink " + r.referenceType.name + "View" + " " + r.name + " <= " + t.name.toFirstLower + "." + r.name + ";\n"
				}

				proposal += "\n\t// tables\n"

				for (r : t.relations.filter[r | r.many]) {
					proposal += "\ttable " + r.referenceType.name + "Table" + " " + r.name + " <= " + t.name.toFirstLower + "." + r.name + ";\n"
				}

				proposal += "}"
				
		  		acceptor.accept(createCompletionProposal(proposal, display, null, context));
			}
		}

		if (model instanceof UIRowDeclaration && (model as UIRowDeclaration).name === null) {
		  	acceptor.accept(createCompletionProposal("Table", context));
			
			for (t : (model.eContainer as ModelDeclaration).transferDeclarations) {
				var String display = t.name + "Table";
				var String proposal = display
				proposal += "(" + t.name + " " + t.name.toFirstLower +") {\n";

				proposal += "\t// columns\n"

				for (f : t.fields) {
					proposal += "\tcolumn " + f.referenceType.name + " " + f.name + " <= " + " " + t.name.toFirstLower + "." + f.name + ";\n"
				}

				proposal += "}"
				
		  		acceptor.accept(createCompletionProposal(proposal, display, null, context));
			}
		}

		if (model instanceof UIMenuDeclaration && (model as UIMenuDeclaration).name === null) {
		  	acceptor.accept(createCompletionProposal("Menu", context));
			
			for (t : (model.eContainer as ModelDeclaration).actorDeclarations) {
				var String display = t.name + "Menu";
				var String proposal = display
				proposal += "(" + t.name + " " + t.name.toFirstLower +") {\n";

				proposal += "\t// links\n"

				for (r : t.relations.filter[r | !r.many]) {
					proposal += "\tlink " + r.referenceType.name + "View" + " " + r.name + " <= " + t.name.toFirstLower + "." + r.name + ";\n"
				}

				proposal += "\n\t// tables\n"

				for (r : t.relations.filter[r | r.many]) {
					proposal += "\ttable " + r.referenceType.name + "Table" + " " + r.name + " <= " + t.name.toFirstLower + "." + r.name + ";\n"
				}

				proposal += "}"
				
		  		acceptor.accept(createCompletionProposal(proposal, display, null, context));
			}
		}
	}

/*
    override completeCreateExpression_Type(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
        lookupCrossReference((assignment.getTerminal() as CrossReference), context, acceptor, [
            false
        ]);
    }
*/
/*     override completeNavigationBase_EnumValue(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
        lookupCrossReference((assignment.getTerminal() as CrossReference), context, acceptor, [
            true
        ]);
    }
*/
}
